export const Url = {
  baseUrl: 'https://elearningapp-api.herokuapp.com',
  verify: '/learn/verify/',
  resend: '/learn/resend/',
  content: '/subject/get/content/',
  pageNum: '?pageSize=1&pageNumber=',
  chapters: '/subject/get/chapters/',
  name: '/subject/get/name',
  homeStudying: '/subject/get/studying',
  subjects: '/subject/get/subjects',
  search: '/subject/search/',
  notifcation: '/subject/notification',
  result: '/subject/get/result',
  profile: '/learn/profile',
  editProfile: '/learn/editprofile',
  setNotif: '/subject/set/notification/',
  getTest: '/subject/gettest/',
  reset: '/learn/reset',
  authenticate: '/learn/authenticate',
  forgot: '/learn/forgot',
  create: '/learn/create',
  courses: '/subject/get/courses/',
  lessons: '/subject/get/lessons/',
  lessonStudying: '/subject/get/lessons/studying',
  beginTest: '/subject/begintest/',
  submitTest: '/subject/submittest',
};